services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 234565
    command: --default-authentication-plugin=mysql_native_password --port=3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - game-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      AUTH_SERVICE_URL: http://auth-service:3000
      GAME_SERVICE_URL: http://game-service:3000
      BASKET_SERVICE_URL: http://basket-service:3000
    volumes:
      - ./game-service/src/assets:/app/src/assets
    depends_on:
      - auth-service
      - game-service
      - basket-service
    networks:
      - game-network

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: auth_user
      DB_PASSWORD: auth_pass
      DB_NAME: auth_service
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - game-network

  game-service:
    build: ./game-service
    ports:
      - "3002:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: game_user
      DB_PASSWORD: game_pass
      DB_NAME: game_service
      NODE_ENV: development
    volumes:
      - ./game-service/src/assets:/app/src/assets
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - game-network

  basket-service:
    build: ./basket-service
    ports:
      - "3003:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: basket_user
      DB_PASSWORD: basket_pass
      DB_NAME: basket_service
      NODE_ENV: development
    volumes:
      - ./game-service/src/assets:/app/src/assets
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - game-network

volumes:
  mysql-data:
  static-files:

networks:
  game-network:
    driver: bridge